ALTER TABLE LEPIDOPTERA.SPECIMEN 
ADD (LOCALITY_ID NUMBER );

ALTER TABLE LEPIDOPTERA.SPECIMEN 
ADD (COLLECTING_EVENT_ID NUMBER );

COMMENT ON COLUMN LEPIDOPTERA.SPECIMEN.LOCALITY_ID IS 'To map to MCZbaase locality.locality_id';

COMMENT ON COLUMN LEPIDOPTERA.SPECIMEN.COLLECTING_EVENT_ID IS 'To map to MCZbase collecting_event.collecting_event_id';

