
  CREATE TABLE "LEPIDOPTERA"."SPECIMEN_PART" 
   (    "SPECIMENPARTID" NUMBER(20,0) NOT NULL ENABLE, 
    "SPECIMENID" NUMBER(20,0) NOT NULL ENABLE, 
    "PART_NAME" VARCHAR2(255 CHAR) DEFAULT 'whole animal' NOT NULL ENABLE, 
    "PRESERVE_METHOD" VARCHAR2(60 CHAR), 
    "LOT_COUNT" NUMBER, 
    "LOT_COUNT_MODIFIER" VARCHAR2(5 CHAR), 
     CONSTRAINT "SPECIMEN_PART_PK" PRIMARY KEY ("SPECIMENPARTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
     CONSTRAINT "SPECIMEN_PART_SPECIMEN_FK1" FOREIGN KEY ("SPECIMENID")
      REFERENCES "LEPIDOPTERA"."SPECIMEN" ("SPECIMENID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."SPECIMEN_PART_TRG" BEFORE INSERT ON SPECIMEN_PART 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.SPECIMENPARTID IS NULL THEN
      SELECT SPECIMEN_PART_SEQ.NEXTVAL INTO :NEW.SPECIMENPARTID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LEPIDOPTERA"."SPECIMEN_PART_TRG" ENABLE;



  CREATE TABLE "LEPIDOPTERA"."SPECIMEN_PART_ATTRIBUTE" 
   (    "SPECIMENPARTATTRIBUTEID" NUMBER(20,0) NOT NULL ENABLE, 
    "SPECIMENPARTID" NUMBER(20,0) NOT NULL ENABLE, 
    "ATTRIBUTE_TYPE" VARCHAR2(30 CHAR), 
    "ATTRIBUTE_VALUE" VARCHAR2(255 CHAR), 
    "ATTRIBUTE_UNITS" VARCHAR2(30 CHAR), 
    "ATTRIBUTE_REMARK" VARCHAR2(4000 CHAR), 
    "ATTRIBUTE_DETERMINER" VARCHAR2(255 CHAR), 
    "ATTRIBUTE_DATE" DATE, 
     CONSTRAINT "SPECIMEN_PART_ATTRIBUTE_PK" PRIMARY KEY ("SPECIMENPARTATTRIBUTEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
     CONSTRAINT "SPECIMEN_PART_ATTRIBUTE_S_FK1" FOREIGN KEY ("SPECIMENPARTID")
      REFERENCES "LEPIDOPTERA"."SPECIMEN_PART" ("SPECIMENPARTID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."SPECIMEN_PART_ATTRIBUTE_TRG" BEFORE INSERT ON SPECIMEN_PART_ATTRIBUTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.SPECIMENPARTATTRIBUTEID IS NULL THEN
      SELECT SPECIMEN_PART_ATTRIBUTE_SEQ.NEXTVAL INTO :NEW.SPECIMENPARTATTRIBUTEID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LEPIDOPTERA"."SPECIMEN_PART_ATTRIBUTE_TRG" ENABLE;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_SPATTR_TIMESTAMP" 
BEFORE INSERT ON SPECIMEN_PART_ATTRIBUTE 
FOR EACH ROW 
BEGIN
    SELECT SYSTIMESTAMP INTO :NEW.ATTRIBUTE_DATE FROM Dual ;
END;
/
ALTER TRIGGER "LEPIDOPTERA"."TRG_SPATTR_TIMESTAMP" ENABLE;

insert into Specimen_Part (SpecimenId, Part_name, Preserve_Method, Lot_Count)
     select specimenid, 'whole animal', lcase(PreparationType), 1 from Specimen;

alter table Specimen drop column PreparationType;
alter table Specimen change column ISODate ISODate varchar(32 CHAR) default '';


--  create public synonym mczbase_geog_auth_rec for geog_auth_rec@mczbase_auth;
create synonym lepidoptera.mczbase_geog_auth_rec for geog_auth_rec@mczbase_auth;


ALTER TABLE LEPIDOPTERA.SPECIMEN 
ADD (HIGHER_GEOGRAPHY VARCHAR2(255 CHAR) );
