REM ======================================================================
REM ===   Sql Script for Database : Lepidoptera MySQL db
REM ===
REM === Build : Actual Build on Crow.
REM === Revised: Changed BYTE to CHAR.  Image.SpecimenId FK disabled. 
REM ======================================================================
REM 

  CREATE TABLE "LEPIDOPTERA"."SPECIMEN" 
   (	"SPECIMENID" NUMBER(20,0), 
	"BARCODE" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"DRAWERNUMBER" VARCHAR2(10 CHAR), 
	"TYPESTATUS" VARCHAR2(50 CHAR) DEFAULT 'Not a Type' NOT NULL ENABLE, 
	"TYPENUMBER" NUMBER(20,0), 
	"CITEDINPUBLICATION" VARCHAR2(900 CHAR), 
	"FEATURES" VARCHAR2(50 CHAR), 
	"FAMILY" VARCHAR2(40 CHAR), 
	"SUBFAMILY" VARCHAR2(40 CHAR), 
	"TRIBE" VARCHAR2(40 CHAR), 
	"GENUS" VARCHAR2(40 CHAR), 
	"SPECIFICEPITHET" VARCHAR2(40 CHAR), 
	"SUBSPECIFICEPITHET" VARCHAR2(255 CHAR), 
	"INFRASPECIFICEPITHET" VARCHAR2(40 CHAR), 
	"INFRASPECIFICRANK" VARCHAR2(40 CHAR), 
	"AUTHORSHIP" VARCHAR2(255 CHAR), 
	"UNNAMEDFORM" VARCHAR2(50 CHAR), 
	"IDENTIFIEDBY" VARCHAR2(255 CHAR), 
	"COUNTRY" VARCHAR2(255 CHAR), 
	"PRIMARYDIVISON" VARCHAR2(255 CHAR), 
	"SPECIFICLOCALITY" VARCHAR2(4000 CHAR), 
	"VERBATIMLOCALITY" VARCHAR2(4000 CHAR), 
	"VERBATIMELEVATION" VARCHAR2(255 CHAR), 
	"COLLECTINGMETHOD" VARCHAR2(255 CHAR), 
	"DATENOS" VARCHAR2(32 CHAR), 
	"DATEEMERGED" VARCHAR2(32 CHAR), 
	"DATEEMERGEDINDICATOR" VARCHAR2(10 CHAR), 
	"DATECOLLECTED" VARCHAR2(32 CHAR), 
	"DATECOLLECTEDINDICATOR" VARCHAR2(10 CHAR), 
	"COLLECTION" VARCHAR2(255 CHAR), 
	"SPECIMENNOTES" VARCHAR2(4000 CHAR), 
	"LIFESTAGE" VARCHAR2(50 CHAR), 
	"SEX" VARCHAR2(50 CHAR), 
	"PREPARATIONTYPE" VARCHAR2(50 CHAR), 
	"HABITAT" VARCHAR2(900 CHAR), 
	"ASSOCIATEDTAXON" VARCHAR2(900 CHAR), 
	"QUESTIONS" VARCHAR2(900 CHAR), 
	"INFERENCES" VARCHAR2(900 CHAR), 
	"LOCATIONINCOLLECTION" VARCHAR2(255 CHAR) DEFAULT 'General Lepidoptera Collection', 
	"WORKFLOWSTATUS" VARCHAR2(30 CHAR), 
	"CREATEDBY" VARCHAR2(255 CHAR), 
	"DATECREATED" TIMESTAMP (6), 
	"DATELASTUPDATED" DATE, 
	"LASTUPDATEDBY" VARCHAR2(255 CHAR), 
	"VALIDDISTRIBUTIONFLAG" CHAR(1 CHAR) DEFAULT 'Y', 
	 PRIMARY KEY ("SPECIMENID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE, 
	 CONSTRAINT "BARCODE_UNIQUE" UNIQUE ("BARCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE UNIQUE INDEX "LEPIDOPTERA"."BARCODE_UNIQUE" ON "LEPIDOPTERA"."SPECIMEN" ("BARCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE UNIQUE INDEX "LEPIDOPTERA"."SYS_C0084308" ON "LEPIDOPTERA"."SPECIMEN" ("SPECIMENID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_SPECIMENID" 
BEFORE INSERT OR UPDATE ON SPECIMEN
FOR EACH ROW
DECLARE
    iCounter SPECIMEN.SpecimenId%TYPE;
    cannot_change_counter EXCEPTION; BEGIN
    IF INSERTING THEN       
       IF :NEW.SpecimenId is null THEN
        SELECT SEQ_SpecimenId.NEXTVAL INTO iCounter FROM Dual ;
        :NEW.SpecimenId := iCounter;
       END IF;
    END IF;
    IF UPDATING THEN
        IF NOT (:NEW.SpecimenId = :OLD.SpecimenId) THEN
            RAISE cannot_change_counter;
        END IF;
    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         RAISE_APPLICATION_ERROR(-20000, 'Cannot Change Counter Value');
END ;


/
ALTER TRIGGER "LEPIDOPTERA"."TRG_SPECIMENID" ENABLE;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_SPEC_TIMESTAMP" 
BEFORE INSERT ON SPECIMEN
FOR EACH ROW 
BEGIN
 SELECT SYSTIMESTAMP INTO :NEW.DATECREATED FROM Dual ;
END;

/
ALTER TRIGGER "LEPIDOPTERA"."TRG_SPEC_TIMESTAMP" ENABLE;
 


REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."DETERMINATION" 
   (	"DETERMINATIONID" NUMBER(20,0), 
	"SPECIMENID" NUMBER(20,0) NOT NULL ENABLE, 
	"GENUS" VARCHAR2(40 CHAR), 
	"SPECIFICEPITHET" VARCHAR2(40 CHAR), 
	"SUBSPECIFICEPITHET" VARCHAR2(255 CHAR), 
	"INFRASPECIFICEPITHET" VARCHAR2(40 CHAR), 
	"INFRASPECIFICRANK" VARCHAR2(40 CHAR), 
	"AUTHORSHIP" VARCHAR2(255 CHAR), 
	"UNNAMEDFORM" VARCHAR2(50 CHAR), 
	"IDENTIFICATIONQUALIFIER" VARCHAR2(50 CHAR), 
	"IDENTIFIEDBY" VARCHAR2(255 CHAR), 
	"TYPESTATUS" VARCHAR2(50 CHAR), 
	 PRIMARY KEY ("DETERMINATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE, 
	 FOREIGN KEY ("SPECIMENID")
	  REFERENCES "LEPIDOPTERA"."SPECIMEN" ("SPECIMENID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE INDEX "LEPIDOPTERA"."DETERMINATIONIDX1" ON "LEPIDOPTERA"."DETERMINATION" ("SPECIMENID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE UNIQUE INDEX "LEPIDOPTERA"."SYS_C0084556" ON "LEPIDOPTERA"."DETERMINATION" ("DETERMINATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_DETERMINATIONID" 
BEFORE INSERT OR UPDATE ON "LEPIDOPTERA".determination
FOR EACH ROW
DECLARE
    iCounter "LEPIDOPTERA".determination.determinationId%TYPE;
    cannot_change_counter EXCEPTION;
BEGIN
    IF INSERTING THEN
      if :NEW.determinationId is null then 
        SELECT SEQ_determinationId.NEXTVAL INTO iCounter FROM Dual;
        :NEW.determinationId := iCounter;
      end if ;
    END IF;
    IF UPDATING THEN
        IF NOT (:NEW.determinationId = :OLD.determinationId) THEN
            RAISE cannot_change_counter;
        END IF;
    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         RAISE_APPLICATION_ERROR(-20000, 'Cannot Change Counter Value');
END;

/
ALTER TRIGGER "LEPIDOPTERA"."TRG_DETERMINATIONID" ENABLE;
 


REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."COLLECTOR" 
   (	"COLLECTORID" NUMBER(20,0), 
	"COLLECTORNAME" VARCHAR2(255 CHAR), 
	"SPECIMENID" NUMBER(20,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("COLLECTORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE, 
	 FOREIGN KEY ("SPECIMENID")
	  REFERENCES "LEPIDOPTERA"."SPECIMEN" ("SPECIMENID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE INDEX "LEPIDOPTERA"."COLLECTORIDX1" ON "LEPIDOPTERA"."COLLECTOR" ("COLLECTORNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE UNIQUE INDEX "LEPIDOPTERA"."SYS_C0084313" ON "LEPIDOPTERA"."COLLECTOR" ("COLLECTORID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_COLLECTORID" 
BEFORE INSERT OR UPDATE ON collector
FOR EACH ROW
DECLARE
    iCounter collector.collectorId%TYPE;
    cannot_change_counter EXCEPTION;
BEGIN
    IF INSERTING THEN
      if :NEW.collectorId is null then
        SELECT SEQ_collectorId.NEXTVAL INTO iCounter FROM Dual;
        :NEW.collectorId := iCounter;
      end if;
    END IF;
    IF UPDATING THEN
        IF NOT (:NEW.collectorId = :OLD.collectorId) THEN
            RAISE cannot_change_counter;
        END IF;
    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         RAISE_APPLICATION_ERROR(-20000, 'Cannot Change Counter Value');
END;

/
ALTER TRIGGER "LEPIDOPTERA"."TRG_COLLECTORID" ENABLE;
 


REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."TRACKING" 
   (	"TRACKINGID" NUMBER(20,0), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"EVENTTYPE" VARCHAR2(40 CHAR), 
	"EVENTDATETIME" DATE, 
	"SPECIMENID" NUMBER(20,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("TRACKINGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE, 
	 FOREIGN KEY ("SPECIMENID")
	  REFERENCES "LEPIDOPTERA"."SPECIMEN" ("SPECIMENID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_TRACK_TIMESTAMP" 
BEFORE INSERT ON TRACKING
FOR EACH ROW 
BEGIN
 SELECT SYSDATE INTO :NEW.EVENTDATETIME FROM Dual ;
END;

/
ALTER TRIGGER "LEPIDOPTERA"."TRG_TRACK_TIMESTAMP" ENABLE;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_TRACKINGID" 
BEFORE INSERT OR UPDATE ON tracking
FOR EACH ROW
DECLARE
    iCounter tracking.trackingId%TYPE;
    cannot_change_counter EXCEPTION;
BEGIN
    IF INSERTING THEN
      if :NEW.trackingId is null then
        SELECT SEQ_trackingId.NEXTVAL INTO iCounter FROM Dual;
        :NEW.trackingId := iCounter;
      end if;
    END IF;
    IF UPDATING THEN
        IF NOT (:NEW.trackingId = :OLD.trackingId) THEN
            RAISE cannot_change_counter;
        END IF;
    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         RAISE_APPLICATION_ERROR(-20000, 'Cannot Change Counter Value');
END;

/
ALTER TRIGGER "LEPIDOPTERA"."TRG_TRACKINGID" ENABLE;
 


REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."OTHER_NUMBERS" 
   (	"NUMBERID" NUMBER(20,0), 
	"OTHER_NUMBER" VARCHAR2(50 CHAR), 
	"NUMBERTYPE" VARCHAR2(50 CHAR), 
	"SPECIMENID" NUMBER(20,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE, 
	 FOREIGN KEY ("SPECIMENID")
	  REFERENCES "LEPIDOPTERA"."SPECIMEN" ("SPECIMENID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_NUMBERID" 
BEFORE INSERT OR UPDATE ON other_numbers
FOR EACH ROW
DECLARE
    iCounter other_numbers.numberId%TYPE;
    cannot_change_counter EXCEPTION;
BEGIN
    IF INSERTING THEN
       if :NEW.numberId is null then 
        SELECT SEQ_numberId.NEXTVAL INTO iCounter FROM Dual;
        :NEW.numberId := iCounter;
       end if ;
    END IF;
    IF UPDATING THEN
        IF NOT (:NEW.numberId = :OLD.numberId) THEN
            RAISE cannot_change_counter;
        END IF;
    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         RAISE_APPLICATION_ERROR(-20000, 'Cannot Change Counter Value');
END;

/
ALTER TRIGGER "LEPIDOPTERA"."TRG_NUMBERID" ENABLE;
 


REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."IMAGE" 
   (	"IMAGEID" NUMBER(20,0), 
	"RAWBARCODE" VARCHAR2(255 CHAR), 
	"RAWEXIFBARCODE" VARCHAR2(255 CHAR), 
	"FILENAME" VARCHAR2(255 CHAR), 
	"RAWOCR" VARCHAR2(4000 CHAR), 
	"PATH" VARCHAR2(900 CHAR), 
	"URI" VARCHAR2(255 CHAR), 
	"SPECIMENID" NUMBER(20,0), 
	"TEMPLATEID" VARCHAR2(255 CHAR), 
	"DRAWERNUMBER" VARCHAR2(10 CHAR), 
	"MD5SUM" VARCHAR2(900 CHAR), 
	 PRIMARY KEY ("IMAGEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE, 
	 FOREIGN KEY ("SPECIMENID")
	  REFERENCES "LEPIDOPTERA"."SPECIMEN" ("SPECIMENID") DISABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE INDEX "LEPIDOPTERA"."IMAGEIDX1" ON "LEPIDOPTERA"."IMAGE" ("RAWBARCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE INDEX "LEPIDOPTERA"."IMAGEIDX2" ON "LEPIDOPTERA"."IMAGE" ("SPECIMENID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE UNIQUE INDEX "LEPIDOPTERA"."SYS_C0084540" ON "LEPIDOPTERA"."IMAGE" ("IMAGEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_IMAGEID" 
BEFORE INSERT OR UPDATE ON image
FOR EACH ROW
DECLARE
    iCounter image.imageId%TYPE;
    cannot_change_counter EXCEPTION;
BEGIN
    IF INSERTING THEN
      if :NEW.imageId is null then 
        SELECT SEQ_imageId.NEXTVAL INTO iCounter FROM Dual;
        :NEW.imageId := iCounter;
      end if;
    END IF;
    IF UPDATING THEN
        IF NOT (:NEW.imageId = :OLD.imageId) THEN
            RAISE cannot_change_counter;
        END IF;
    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         RAISE_APPLICATION_ERROR(-20000, 'Cannot Change Counter Value');
END;

/
ALTER TRIGGER "LEPIDOPTERA"."TRG_IMAGEID" ENABLE;
 


REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."USERS" 
   (	"USERID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(255 CHAR) DEFAULT '' NOT NULL ENABLE, 
	"FULLNAME" VARCHAR2(50 CHAR) DEFAULT '' NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"ROLE" VARCHAR2(20 CHAR) DEFAULT 'Data Entry' NOT NULL ENABLE, 
	"HASH" VARCHAR2(41 CHAR), 
	 PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE, 
	 CONSTRAINT "U_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE UNIQUE INDEX "LEPIDOPTERA"."SYS_C0084545" ON "LEPIDOPTERA"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE UNIQUE INDEX "LEPIDOPTERA"."U_USERNAME" ON "LEPIDOPTERA"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."TRG_USERID" 
BEFORE INSERT OR UPDATE ON users
FOR EACH ROW
DECLARE
    iCounter users.userId%TYPE;
    cannot_change_counter EXCEPTION;
BEGIN
    IF INSERTING THEN
      if :NEW.userId is null then 
        SELECT SEQ_userId.NEXTVAL INTO iCounter FROM Dual;
        :NEW.userId := iCounter;
      end if;
    END IF;
    IF UPDATING THEN
        IF NOT (:NEW.userId = :OLD.userId) THEN
            RAISE cannot_change_counter;
        END IF;
    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         RAISE_APPLICATION_ERROR(-20000, 'Cannot Change Counter Value');
END;

/
ALTER TRIGGER "LEPIDOPTERA"."TRG_USERID" ENABLE;
 


REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."TEMPLATE" 
   (	"TEMPLATEID" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"TEMPLATE_NAME" VARCHAR2(255 CHAR), 
	"IMAGESIZEX" NUMBER(10,0), 
	"IMAGESIZEY" NUMBER(10,0), 
	"BARCODEPOSITIONX" NUMBER(10,0), 
	"BARCODEPOSITIONY" NUMBER(10,0), 
	"BARCODESIZEX" NUMBER(10,0), 
	"BARCODESIZEY" NUMBER(10,0), 
	"SPECIMENPOSITIONX" NUMBER(10,0), 
	"SPECIMENPOSITIONY" NUMBER(10,0), 
	"SPECIMENSIZEX" NUMBER(10,0), 
	"SPECIMENSIZEY" NUMBER(10,0), 
	"TEXTPOSITIONX" NUMBER(10,0), 
	"TEXTPOSITIONY" NUMBER(10,0), 
	"TEXTSIZEX" NUMBER(10,0), 
	"TEXTSIZEY" NUMBER(10,0), 
	"LABELPOSITIONX" NUMBER(10,0), 
	"LABELPOSITIONY" NUMBER(10,0), 
	"LABELSIZEX" NUMBER(10,0), 
	"LABELSIZEY" NUMBER(10,0), 
	"UTLABELPOSITIONX" NUMBER(10,0), 
	"UTLABELPOSITIONY" NUMBER(10,0), 
	"UTLABELSIZEX" NUMBER(10,0), 
	"UTLABELSIZEY" NUMBER(10,0), 
	"ENABLED" CHAR(1) DEFAULT 'Y',
	"REFERENCEIMAGE" NUMBER(20,0),
	 PRIMARY KEY ("TEMPLATEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 


REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."HIGHER_TAXON" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FAMILY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SUBFAMILY" VARCHAR2(255 CHAR), 
	"TRIBE" VARCHAR2(255 CHAR), 
	 CONSTRAINT "HIGHER_TAXON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE UNIQUE INDEX "LEPIDOPTERA"."HIGHER_TAXON_PK" ON "LEPIDOPTERA"."HIGHER_TAXON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE INDEX "LEPIDOPTERA"."HIGHER_TAXON_SUBFAMILY" ON "LEPIDOPTERA"."HIGHER_TAXON" ("FAMILY", "SUBFAMILY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE INDEX "LEPIDOPTERA"."HIGHER_TAXON_TRIBE" ON "LEPIDOPTERA"."HIGHER_TAXON" ("FAMILY", "SUBFAMILY", "TRIBE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."HIGHER_TAXON_TRG" 
BEFORE INSERT ON HIGHER_TAXON
FOR EACH ROW 
BEGIN
  SELECT HIGHER_TAXON_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

ALTER TRIGGER "LEPIDOPTERA"."HIGHER_TAXON_TRG" ENABLE;

REM ======================================================================


  CREATE TABLE "LEPIDOPTERA"."UNIT_TRAY_LABEL" 
   (	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FAMILY" VARCHAR2(40 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"SUBFAMILY" VARCHAR2(40 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"TRIBE" VARCHAR2(40 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"GENUS" VARCHAR2(40 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"SPECIFICEPITHET" VARCHAR2(40 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"SUBSPECIFICEPITHET" VARCHAR2(255 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"INFRASPECIFICEPITHET" VARCHAR2(40 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"INFRASPECIFICRANK" VARCHAR2(40 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"AUTHORSHIP" VARCHAR2(255 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"UNNAMEDFORM" VARCHAR2(40 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"DRAWERNUMBER" VARCHAR2(10 BYTE) DEFAULT '' NOT NULL ENABLE, 
	"PRINTED" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "UNIT_TRAY_LABEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE INDEX "LEPIDOPTERA"."UNIT_TRAY_LABEL_INDEX1" ON "LEPIDOPTERA"."UNIT_TRAY_LABEL" ("FAMILY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE INDEX "LEPIDOPTERA"."UNIT_TRAY_LABEL_INDEX2" ON "LEPIDOPTERA"."UNIT_TRAY_LABEL" ("SUBFAMILY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE INDEX "LEPIDOPTERA"."UNIT_TRAY_LABEL_INDEX3" ON "LEPIDOPTERA"."UNIT_TRAY_LABEL" ("TRIBE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE INDEX "LEPIDOPTERA"."UNIT_TRAY_LABEL_INDEX4" ON "LEPIDOPTERA"."UNIT_TRAY_LABEL" ("GENUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE INDEX "LEPIDOPTERA"."UNIT_TRAY_LABEL_INDEX5" ON "LEPIDOPTERA"."UNIT_TRAY_LABEL" ("SPECIFICEPITHET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE INDEX "LEPIDOPTERA"."UNIT_TRAY_LABEL_INDEX_HIGHER" ON "LEPIDOPTERA"."UNIT_TRAY_LABEL" ("FAMILY", "SUBFAMILY", "TRIBE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 
  CREATE UNIQUE INDEX "LEPIDOPTERA"."UNIT_TRAY_LABEL_PK" ON "LEPIDOPTERA"."UNIT_TRAY_LABEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_1" ;
 

  CREATE OR REPLACE TRIGGER "LEPIDOPTERA"."UNIT_TRAY_LABEL_TRG" 
BEFORE INSERT ON UNIT_TRAY_LABEL
FOR EACH ROW 
BEGIN
  SELECT UNIT_TRAY_LABEL_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "LEPIDOPTERA"."UNIT_TRAY_LABEL_TRG" ENABLE;
 
