package edu.harvard.mcz.imagecapture.data;

// Generated Feb 27, 2009 8:34:09 AM by Hibernate Tools 3.2.2.GA

/**
 * Template generated by hbm2java
 */
public class Template implements java.io.Serializable {

	private static final long serialVersionUID = -7457138600715862183L;
	
	private String templateId;
	private String name;
	private Integer imageSizeX;
	private Integer imageSizeY;
	private Integer barcodePositionX;
	private Integer barcodePositionY;
	private Integer barcodeSizeX;
	private Integer barcodeSizeY;
	private Integer specimenPositionX;
	private Integer specimenPositionY;
	private Integer specimenSizeX;
	private Integer specimenSizeY;
	private Integer textPositionX;
	private Integer textPositionY;
	private Integer textSizeX;
	private Integer textSizeY;
	private Integer labelPositionX;
	private Integer labelPositionY;
	private Integer labelSizeX;
	private Integer labelSizeY;
	private Integer utLabelPositionX;
	private Integer utLabelPositionY;
	private Integer utLabelSizeX;
	private Integer utLabelSizey;
	private Integer utBarcodePositionX;
	private Integer utBarcodePositionY;
	private Integer utBarcodeSizeX;
	private Integer utBarcodeSizeY;	
	private boolean editable;
	private ICImage referenceImage;

	public Template() {
	}

	public Template(String templateId) {
		this.templateId = templateId;
	}

	public Template(String templateId, String name, Integer imageSizeX,
			Integer imageSizeY, Integer barcodePositionX,
			Integer barcodePositionY, Integer barcodeSizeX,
			Integer barcodeSizeY, Integer specimenPositionX,
			Integer specimenPositionY, Integer specimenSizeX,
			Integer specimenSizeY, Integer textPositionX,
			Integer textPositionY, Integer textSizeX, Integer textSizeY,
			Integer labelPositionX, Integer labelPositionY, Integer labelSizeX,
			Integer labelSizeY, Integer utLabelPositionX,
			Integer utLabelPositionY, Integer utLabelSizeX, Integer utLabelSizey, 
			boolean editable, ICImage referenceImage,
			Integer utBarcodePositionY, Integer utBarcodeSizeX, Integer utBarcodeSizeY
			) {
		this.templateId = templateId;
		this.name = name;
		this.imageSizeX = imageSizeX;
		this.imageSizeY = imageSizeY;
		this.barcodePositionX = barcodePositionX;
		this.barcodePositionY = barcodePositionY;
		this.barcodeSizeX = barcodeSizeX;
		this.barcodeSizeY = barcodeSizeY;
		this.specimenPositionX = specimenPositionX;
		this.specimenPositionY = specimenPositionY;
		this.specimenSizeX = specimenSizeX;
		this.specimenSizeY = specimenSizeY;
		this.textPositionX = textPositionX;
		this.textPositionY = textPositionY;
		this.textSizeX = textSizeX;
		this.textSizeY = textSizeY;
		this.labelPositionX = labelPositionX;
		this.labelPositionY = labelPositionY;
		this.labelSizeX = labelSizeX;
		this.labelSizeY = labelSizeY;
		this.utLabelPositionX = utLabelPositionX;
		this.utLabelPositionY = utLabelPositionY;
		this.utLabelSizeX = utLabelSizeX;
		this.utLabelSizey = utLabelSizey;
		this.utBarcodePositionX = utLabelPositionX;
		this.utBarcodePositionY = utLabelPositionY;
		this.utBarcodeSizeX = utBarcodeSizeX;
		this.utBarcodeSizeY = utBarcodeSizeY;
		this.editable = editable;
		this.referenceImage = referenceImage;
	}

	public String getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getImageSizeX() {
		return this.imageSizeX;
	}

	public void setImageSizeX(Integer imageSizeX) {
		this.imageSizeX = imageSizeX;
	}

	public Integer getImageSizeY() {
		return this.imageSizeY;
	}

	public void setImageSizeY(Integer imageSizeY) {
		this.imageSizeY = imageSizeY;
	}

	public Integer getBarcodePositionX() {
		return this.barcodePositionX;
	}

	public void setBarcodePositionX(Integer barcodePositionX) {
		this.barcodePositionX = barcodePositionX;
	}

	public Integer getBarcodePositionY() {
		return this.barcodePositionY;
	}

	public void setBarcodePositionY(Integer barcodePositionY) {
		this.barcodePositionY = barcodePositionY;
	}

	public Integer getBarcodeSizeX() {
		return this.barcodeSizeX;
	}

	public void setBarcodeSizeX(Integer barcodeSizeX) {
		this.barcodeSizeX = barcodeSizeX;
	}

	public Integer getBarcodeSizeY() {
		return this.barcodeSizeY;
	}

	public void setBarcodeSizeY(Integer barcodeSizeY) {
		this.barcodeSizeY = barcodeSizeY;
	}

	public Integer getSpecimenPositionX() {
		return this.specimenPositionX;
	}

	public void setSpecimenPositionX(Integer specimenPositionX) {
		this.specimenPositionX = specimenPositionX;
	}

	public Integer getSpecimenPositionY() {
		return this.specimenPositionY;
	}

	public void setSpecimenPositionY(Integer specimenPositionY) {
		this.specimenPositionY = specimenPositionY;
	}

	public Integer getSpecimenSizeX() {
		return this.specimenSizeX;
	}

	public void setSpecimenSizeX(Integer specimenSizeX) {
		this.specimenSizeX = specimenSizeX;
	}

	public Integer getSpecimenSizeY() {
		return this.specimenSizeY;
	}

	public void setSpecimenSizeY(Integer specimenSizeY) {
		this.specimenSizeY = specimenSizeY;
	}

	public Integer getTextPositionX() {
		return this.textPositionX;
	}

	public void setTextPositionX(Integer textPositionX) {
		this.textPositionX = textPositionX;
	}

	public Integer getTextPositionY() {
		return this.textPositionY;
	}

	public void setTextPositionY(Integer textPositionY) {
		this.textPositionY = textPositionY;
	}

	public Integer getTextSizeX() {
		return this.textSizeX;
	}

	public void setTextSizeX(Integer textSizeX) {
		this.textSizeX = textSizeX;
	}

	public Integer getTextSizeY() {
		return this.textSizeY;
	}

	public void setTextSizeY(Integer textSizeY) {
		this.textSizeY = textSizeY;
	}

	public Integer getLabelPositionX() {
		return this.labelPositionX;
	}

	public void setLabelPositionX(Integer labelPositionX) {
		this.labelPositionX = labelPositionX;
	}

	public Integer getLabelPositionY() {
		return this.labelPositionY;
	}

	public void setLabelPositionY(Integer labelPositionY) {
		this.labelPositionY = labelPositionY;
	}

	public Integer getLabelSizeX() {
		return this.labelSizeX;
	}

	public void setLabelSizeX(Integer labelSizeX) {
		this.labelSizeX = labelSizeX;
	}

	public Integer getLabelSizeY() {
		return this.labelSizeY;
	}

	public void setLabelSizeY(Integer labelSizeY) {
		this.labelSizeY = labelSizeY;
	}

	public Integer getUtLabelPositionX() {
		return this.utLabelPositionX;
	}

	public void setUtLabelPositionX(Integer utLabelPositionX) {
		this.utLabelPositionX = utLabelPositionX;
	}

	public Integer getUtLabelPositionY() {
		return this.utLabelPositionY;
	}

	public void setUtLabelPositionY(Integer utLabelPositionY) {
		this.utLabelPositionY = utLabelPositionY;
	}

	public Integer getUtLabelSizeX() {
		return this.utLabelSizeX;
	}

	public void setUtLabelSizeX(Integer utLabelSizeX) {
		this.utLabelSizeX = utLabelSizeX;
	}

	public Integer getUtLabelSizey() {
		return this.utLabelSizey;
	}

	public void setUtLabelSizey(Integer utLabelSizey) {
		this.utLabelSizey = utLabelSizey;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
	}

	public boolean getEditable() {
		return editable;
	}

	public void setReferenceImage(ICImage referenceImage) {
		this.referenceImage = referenceImage;
	}

	public ICImage getReferenceImage() {
		return referenceImage;
	}

	public void setUtBarcodePositionX(Integer utBarcodePositionX) {
		this.utBarcodePositionX = utBarcodePositionX;
	}

	public Integer getUtBarcodePositionX() {
		return utBarcodePositionX;
	}

	public void setUtBarcodePositionY(Integer utBarcodePositionY) {
		this.utBarcodePositionY = utBarcodePositionY;
	}

	public Integer getUtBarcodePositionY() {
		return utBarcodePositionY;
	}

	public void setUtBarcodeSizeX(Integer utBarcodeSizeX) {
		this.utBarcodeSizeX = utBarcodeSizeX;
	}

	public Integer getUtBarcodeSizeX() {
		return utBarcodeSizeX;
	}

	public void setUtBarcodeSizeY(Integer utBarcodeSizeY) {
		this.utBarcodeSizeY = utBarcodeSizeY;
	}

	public Integer getUtBarcodeSizeY() {
		return utBarcodeSizeY;
	}

}
