package edu.harvard.mcz.imagecapture.data;

// Generated Jan 23, 2009 8:12:35 AM by Hibernate Tools 3.2.2.GA

/**
 * Collector generated by hbm2java
 */
public class Collector implements java.io.Serializable {

	private static final long serialVersionUID = 4879266496355071312L;
	
	private Long collectorId;
	private Specimen specimen;
	private String collectorName;

	public Collector() {
	}

	public Collector(Specimen specimen) {
		this.specimen = specimen;
	}

	public Collector(Specimen specimen, String collectorName) {
		this.specimen = specimen;
		this.collectorName = collectorName;
	}

	public Long getCollectorId() {
		return this.collectorId;
	}

	public void setCollectorId(Long collectorId) {
		this.collectorId = collectorId;
	}

	public Specimen getSpecimen() {
		return this.specimen;
	}

	public void setSpecimen(Specimen specimen) {
		this.specimen = specimen;
	}

	public String getCollectorName() {
		return this.collectorName;
	}

	public void setCollectorName(String collectorName) {
		this.collectorName = collectorName;
	}

}
