package edu.harvard.mcz.imagecapture.data;

// Generated Jan 23, 2009 8:12:35 AM by Hibernate Tools 3.2.2.GA

/**
 * ICImage generated by hbm2java
 */
public class ICImage implements java.io.Serializable {

	private static final long serialVersionUID = -6798658217903637142L;
	
	private Long imageId;
	private Specimen specimen;
	private String rawBarcode;
	private String rawExifBarcode;
	private String filename;
	private String rawOcr;
	private String path;
	private String uri;
	private String templateId;
	private String drawerNumber;

	public ICImage() {
	}

	public ICImage(Specimen specimen) {
		this.specimen = specimen;
	}

	public ICImage(Specimen specimen, String rawBarcode, String rawExifBarcode, String filename,
			String rawOcr, String path, String uri, String templateId, String drawerNumber) {
		this.specimen = specimen;
		this.rawBarcode = rawBarcode;
		this.rawExifBarcode = rawExifBarcode;
		this.filename = filename;
		setRawOcr(rawOcr);
		this.path = path;
		this.uri = uri;
		this.templateId = templateId;
		setDrawerNumber(drawerNumber);
	}

	public Long getImageId() {
		return this.imageId;
	}

	public void setImageId(Long imageId) {
		this.imageId = imageId;
	}

	public Specimen getSpecimen() {
		return this.specimen;
	}

	public void setSpecimen(Specimen specimen) {
		this.specimen = specimen;
	}

	public String getRawBarcode() {
		return this.rawBarcode;
	}

	public void setRawBarcode(String rawBarcode) {
		this.rawBarcode = rawBarcode;
	    if (this.rawBarcode!=null && this.rawBarcode.length() > MetadataRetriever.getFieldLength(ICImage.class, "rawBarcode")) { 
	        this.rawBarcode = this.rawBarcode.substring(0, MetadataRetriever.getFieldLength(ICImage.class, "rawBarcode")); 
	    }
	}
	
	public String getRawExifBarcode() {
		return this.rawExifBarcode;
	}

	public void setRawExifBarcode(String rawExifBarcode) {
		this.rawExifBarcode = rawExifBarcode;
	    if (this.rawExifBarcode!=null && this.rawExifBarcode.length() > MetadataRetriever.getFieldLength(ICImage.class, "rawExifBarcode")) { 
	        this.rawExifBarcode = this.rawExifBarcode.substring(0, MetadataRetriever.getFieldLength(ICImage.class, "rawExifBarcode")); 
	    }		
	}	

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getRawOcr() {
		return this.rawOcr;
	}

	public void setRawOcr(String rawOcr) {
		this.rawOcr = rawOcr;
	    if (this.rawOcr!=null && this.rawOcr.length() > MetadataRetriever.getFieldLength(ICImage.class, "rawOcr")) { 
	        this.rawOcr = this.rawOcr.substring(0, MetadataRetriever.getFieldLength(ICImage.class, "rawOcr")); 
	    }		
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public String getTemplateId() {
		return templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	/**
	 * @return the drawerNumber
	 */
	public String getDrawerNumber() {
		return drawerNumber;
	}

	/**
	 * @param drawerNumber the drawerNumber to set
	 */
	public void setDrawerNumber(String drawerNumber) {
		this.drawerNumber = drawerNumber;
	    if (this.drawerNumber!=null && this.drawerNumber.length() > MetadataRetriever.getFieldLength(ICImage.class, "drawerNumber")) { 
	        this.drawerNumber = this.drawerNumber.substring(0, MetadataRetriever.getFieldLength(ICImage.class, "drawerNumber")); 
	    }	
	}
	
}
